INSERT INTO QUESTION_ANSWERING_TYPES(type_name) VALUES('TEXT_ENCODING');
INSERT INTO QUESTION_ANSWERING_TYPES(type_name) VALUES('INT_ENCODING');
INSERT INTO QUESTION_ANSWERING_TYPES(type_name) VALUES('TWO_CHOICES');
INSERT INTO QUESTION_ANSWERING_TYPES(type_name) VALUES('FOUR_CHOICES');

INSERT INTO INFORMATION_CHUNK_TYPES(type_name) VALUES('TEXT');
INSERT INTO INFORMATION_CHUNK_TYPES(type_name) VALUES('IMG_URL');
INSERT INTO INFORMATION_CHUNK_TYPES(type_name) VALUES('VIDEO_URL');
INSERT INTO INFORMATION_CHUNK_TYPES(type_name) VALUES('SOUND_URL');