DROP TABLE information_chunk_types;
DROP TABLE information_chunks;
DROP TABLE information_blocks;
DROP TABLE questions;
DROP TABLE alternate_answers;
DROP TABLE question_answering_types;
DROP TABLE quizz;
DROP TABLE quizz_questions;
DROP TABLE quizz_sessions;
DROP TABLE quizz_session_questions;

CREATE TABLE information_chunk_types (
    information_chunk_type_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_name VARCHAR(50) NOT NULL
);

CREATE TABLE information_chunks(
    information_chunk_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chunk_data VARCHAR(500) NOT NULL,
    information_chunk_type_id INT NOT NULL,
    information_block_id INT
);

CREATE TABLE information_blocks(
    information_block_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
);

CREATE TABLE questions(
    question_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    statement_id INT NOT NULL,
    answer_id INT NOT NULL
);

CREATE TABLE alternate_answers(
    question_id INT NOT NULL,
    information_block_id INT NOT NULL
);

CREATE TABLE question_answering_types(
    question_answering_type_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_name VARCHAR(50)
);

CREATE TABLE quizz(
    quizz_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quizz_name VARCHAR(150)
);

CREATE TABLE quizz_questions(
    quizz_id INT NOT NULL,
    question_id INT NOT NULL,
    points INT NOT NULL,
    question_time INT
);

CREATE TABLE quizz_sessions(
    quizz_session_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quizz_id INT
);

CREATE TABLE quizz_session_questions(
    quizz_session_id INT NOT NULL,
    quizz_question_id INT NOT NULL
);


CREATE TABLE chunk_tables(
    chunk_table_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    table_name VARCHAR(150)
);

CREATE TABLE chunk_tables_column_type(
    chunk_table_column_type_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chunk_table_id INT NOT NULL,
    information_chunk_type_id INT NOT NULL
);



CREATE TABLE chunk_table_positions(
    chunk_table_position_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chunk_table_id INT NOT NULL,
    column_position INT NOT NULL,
    line_position INT NOT NULL
);